version: "3"
services:

  db:
    image: mongo
    volumes:
      - db-data:/data/db
    networks:
      - backend

  grpc-server:
    build: server/
    ports:
      - "50051:50051"
    networks:
      - backend

networks:
  backend:

volumes:
  db-data: