# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: expenses.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='expenses.proto',
  package='expsenses',
  syntax='proto3',
  serialized_options=b'\n\020io.grpc.expensesB\rExpensesProtoP\001\242\002\003HLW',
  serialized_pb=b'\n\x0e\x65xpenses.proto\x12\texpsenses\"\x16\n\x14MultiExpensesRequest\"9\n\x11MultiExpenseReply\x12$\n\x08\x65xpenses\x18\x01 \x03(\x0b\x32\x12.expsenses.Expense\"#\n\x0e\x45xpenseRequest\x12\x11\n\texpenseID\x18\x02 \x01(\t\"q\n\x07\x45xpense\x12\x11\n\texpenseID\x18\x01 \x01(\t\x12\x10\n\x08winkelID\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x02\x12\x0f\n\x07summary\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x0e\n\x06userID\x18\x06 \x01(\t2\xdf\x01\n\x08\x45xpenses\x12S\n\x10GetMultiExpenses\x12\x1f.expsenses.MultiExpensesRequest\x1a\x1c.expsenses.MultiExpenseReply\"\x00\x12@\n\rGetOneExpense\x12\x19.expsenses.ExpenseRequest\x1a\x12.expsenses.Expense\"\x00\x12<\n\x10\x43reateOneExpense\x12\x12.expsenses.Expense\x1a\x12.expsenses.Expense\"\x00\x42)\n\x10io.grpc.expensesB\rExpensesProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_MULTIEXPENSESREQUEST = _descriptor.Descriptor(
  name='MultiExpensesRequest',
  full_name='expsenses.MultiExpensesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=51,
)


_MULTIEXPENSEREPLY = _descriptor.Descriptor(
  name='MultiExpenseReply',
  full_name='expsenses.MultiExpenseReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expenses', full_name='expsenses.MultiExpenseReply.expenses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=110,
)


_EXPENSEREQUEST = _descriptor.Descriptor(
  name='ExpenseRequest',
  full_name='expsenses.ExpenseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expenseID', full_name='expsenses.ExpenseRequest.expenseID', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=147,
)


_EXPENSE = _descriptor.Descriptor(
  name='Expense',
  full_name='expsenses.Expense',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expenseID', full_name='expsenses.Expense.expenseID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winkelID', full_name='expsenses.Expense.winkelID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='expsenses.Expense.price', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='summary', full_name='expsenses.Expense.summary', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='expsenses.Expense.timestamp', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userID', full_name='expsenses.Expense.userID', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=262,
)

_MULTIEXPENSEREPLY.fields_by_name['expenses'].message_type = _EXPENSE
DESCRIPTOR.message_types_by_name['MultiExpensesRequest'] = _MULTIEXPENSESREQUEST
DESCRIPTOR.message_types_by_name['MultiExpenseReply'] = _MULTIEXPENSEREPLY
DESCRIPTOR.message_types_by_name['ExpenseRequest'] = _EXPENSEREQUEST
DESCRIPTOR.message_types_by_name['Expense'] = _EXPENSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MultiExpensesRequest = _reflection.GeneratedProtocolMessageType('MultiExpensesRequest', (_message.Message,), {
  'DESCRIPTOR' : _MULTIEXPENSESREQUEST,
  '__module__' : 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:expsenses.MultiExpensesRequest)
  })
_sym_db.RegisterMessage(MultiExpensesRequest)

MultiExpenseReply = _reflection.GeneratedProtocolMessageType('MultiExpenseReply', (_message.Message,), {
  'DESCRIPTOR' : _MULTIEXPENSEREPLY,
  '__module__' : 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:expsenses.MultiExpenseReply)
  })
_sym_db.RegisterMessage(MultiExpenseReply)

ExpenseRequest = _reflection.GeneratedProtocolMessageType('ExpenseRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPENSEREQUEST,
  '__module__' : 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:expsenses.ExpenseRequest)
  })
_sym_db.RegisterMessage(ExpenseRequest)

Expense = _reflection.GeneratedProtocolMessageType('Expense', (_message.Message,), {
  'DESCRIPTOR' : _EXPENSE,
  '__module__' : 'expenses_pb2'
  # @@protoc_insertion_point(class_scope:expsenses.Expense)
  })
_sym_db.RegisterMessage(Expense)


DESCRIPTOR._options = None

_EXPENSES = _descriptor.ServiceDescriptor(
  name='Expenses',
  full_name='expsenses.Expenses',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=265,
  serialized_end=488,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMultiExpenses',
    full_name='expsenses.Expenses.GetMultiExpenses',
    index=0,
    containing_service=None,
    input_type=_MULTIEXPENSESREQUEST,
    output_type=_MULTIEXPENSEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetOneExpense',
    full_name='expsenses.Expenses.GetOneExpense',
    index=1,
    containing_service=None,
    input_type=_EXPENSEREQUEST,
    output_type=_EXPENSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateOneExpense',
    full_name='expsenses.Expenses.CreateOneExpense',
    index=2,
    containing_service=None,
    input_type=_EXPENSE,
    output_type=_EXPENSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXPENSES)

DESCRIPTOR.services_by_name['Expenses'] = _EXPENSES

# @@protoc_insertion_point(module_scope)
